version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      METAPHOR_API_KEY: ${METAPHOR_API_KEY}
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/app:/code/app
    restart: always
    ports:
      - 8000:8000
